services:
  db:
    image: mariadb
    container_name: snapguard-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'snapguard-root'
    ports:
      - 3306:3306
    volumes:
      - snapguard-db:/var/lib/mysql
  adminer:
    image: adminer
    container_name: snapguard-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  mqtt:
    image: eclipse-mosquitto
    container_name: snapguard-mqtt
    ports:
      - 1883:1883
    volumes:
      - snapguard-mqtt-config:/mosquitto/config

volumes:
  snapguard-db:
  snapguard-mqtt-config:
